language: php

php:
  - 7.2
  - nightly

arch:
  - amd64
  - ppc64le

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - composer self-update
  - composer update 
  - composer install --dev --prefer-source

script:
  - ./vendor/bin/phpstan analyse
  - ./vendor/bin/phpstan analyse -c phpstan.tests.neon
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
  - ./vendor/bin/phpcs

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - CODECLIMATE_REPO_TOKEN=269a392c7a845b5ca031f9412f44435c0ec9ceebd0e19f97ff1762e6f880ba79 ./vendor/bin/test-reporter --coverage-report=coverage.clover

notifications:
  email: true
